enum EventType {
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    CREATE_REVIEW = 'CREATE_REVIEW',
    DELETE_REVIEW = 'DELETE_REVIEW',
    LAUNCH_DISCOUNT = 'LAUNCH_DISCOUNT',
    END_DISCOUNT = 'END_DISCOUNT',
}

export default EventType;