export enum RPCTypes {
    GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID',
    RESERVE_PRODUCT_VARIANT_QUANTITY = 'RESERVE_PRODUCT_VARIANT',
    FILTER_PRODUCT_BY_COLOR_AND_SIZE = 'FILTER_PRODUCT_BY_COLOR_AND_SIZE',
    INVENTORY_CREATE_VARIANT = 'INVENTORY_CREATE_VARIANT',
    INVENTORY_UPDATE_VARIANT = 'INVENTORY_UPDATE_VARIANT',
}

export type CreateProductRPCResponse = {
    status: string,
    message: string,
}