export enum RPCTypes {
    GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID',
    RESERVE_PRODUCT_VARIANT_QUANTITY = 'RESERVE_PRODUCT_VARIANT',
    GET_PRODUCT_VARIANT_LIST_BY_ID_LIST = 'GET_PRODUCT_VARIANT_LIST_BY_ID_LIST',
    GET_PRODUCT_VARIANT_BY_PRODUCT_ID_COLOR_SIZE = 'GET_PRODUCT_VARIANT_BY_PRODUCT_ID_COLOR_SIZE',
}