enum EventType {
    DELETE_USER = 'DELETE_USER',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    CREATE_REVIEW = 'CREATE_REVIEW',
    DELETE_REVIEW = 'DELETE_REVIEW',
    CUSTOMER_ORDER_SUCCESS = 'CUSTOMER_ORDER_SUCCESS',
}

export default EventType;
